[IR] Expose convenience functions and set module name as public (#1581)
We modify the `__module__` property for all public apis so that their
modules appear correctly in documentation.

Added test similar to PyTorch that checks for public apis in the IR and
fixed errors. Example errors:

```
======================================================================
FAIL: test_correct_module_names (__main__.TestPublicApiNamespace.test_correct_module_names)
An API is considered public, if  its  `__module__` starts with `onnxscript.ir`
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/justinchu/dev/onnxscript/tests/ir/public_api_test.py", line 182, in test_correct_module_names
    self.assertTrue(not failure_list, msg)
AssertionError: False is not true : Make sure that everything that is public is expected (in particular that the module has a properly populated `__all__` attribute) and that everything that is supposed to be public does look public (it does not start with `_` and has a `__module__` that is properly populated).

Full list:
# onnxscript.ir.serde.deserialize_dimension:
  - Is NOT public: it is not inside the module's (`onnxscript.ir.serde`) `__all__`
  - Does look public: it does look public because it follows the rules from the doc above (does not start with `_` and has a proper `__module__`).
  - You can do either of these two things to fix this problem:
    - To make it public: add it from the modules's (`onnxscript.ir.serde`) `__all__`
    - To make it NOT look public: make its name start with `_`
# onnxscript.ir.serde.deserialize_metadata_props:
  - Is NOT public: it is not inside the module's (`onnxscript.ir.serde`) `__all__`
  - Does look public: it does look public because it follows the rules from the doc above (does not start with `_` and has a proper `__module__`).
  - You can do either of these two things to fix this problem:
    - To make it public: add it from the modules's (`onnxscript.ir.serde`) `__all__`
    - To make it NOT look public: make its name start with `_`
```