Fix _attribute_value type handling | fix(onnx_export) (#409)
It appears `AttributeProto.HasField` is returning returning false in
some cases. Change to always return the value through the appropriate
field based on `AttributeProto.type`.

### Repro


```python
from onnxscript import script
from onnxscript.onnx_opset import opset15 as op
from onnxscript.onnx_types import FLOAT
from onnxscript.backend.onnx_export import export2python

@script()
def CustomArgMax(X: FLOAT, int_attr: int = 0) -> FLOAT:
    return op.ArgMax(X, axis=int_attr)

print(export2python(CustomArgMax.to_model_proto()))
```

### Exception

```
...

  File "/Users/aaron/src/onnx-script/onnxscript/backend/onnx_export.py", line 172, in _attribute_value
    raise NotImplementedError(f"Unable to return a value for attribute {attr!r}.")
NotImplementedError: Unable to return a value for attribute name: "axis"
type: INT
ref_attr_name: "int_attr"
.
```

Co-authored-by: Justin Chu <justinchuby@users.noreply.github.com>